# Generated by Django 2.1.7 on 2019-05-02 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number entered in the format:'+919999999999'. Up to 14 digits number", regex='^\\+?1?\\d{9,14}$')])),
                ('password', models.CharField(max_length=124)),
                ('create_applications', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
