# Generated by Django 2.1.7 on 2019-05-04 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number entered in the format:'+919999999999'. Up to 14 digits number", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
