# Generated by Django 2.1.7 on 2019-04-27 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number entered in the format:'+919999999999'. Up to 14 digits number", regex='^\\+?1?\\d{9,14}$')])),
                ('alternate_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number entered in the format:'+919999999999'. Up to 14 digits number", regex='^\\+?1?\\d{9,14}$')])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sureame', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('candidate_location', models.CharField(blank=True, max_length=512, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('job_interest', models.CharField(blank=True, max_length=512, null=True)),
                ('candidates_edu', models.CharField(blank=True, max_length=512, null=True)),
                ('college_name', models.CharField(blank=True, max_length=512, null=True)),
                ('name_of_degree', models.CharField(blank=True, max_length=512, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=512, null=True)),
                ('candidate_experience', models.CharField(blank=True, max_length=512, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=512, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=512, null=True)),
                ('candidate_job_role', models.CharField(blank=True, max_length=512, null=True)),
                ('languege_knows', models.CharField(blank=True, max_length=1024, null=True)),
                ('add_skills', models.TextField(blank=True, max_length=1024, null=True)),
                ('sms_notification', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('sessionid', models.CharField(blank=True, max_length=512, null=True)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
