# Generated by Django 2.1.7 on 2019-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidates_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_jobs',
            old_name='languege_knows',
            new_name='languege_can_speak_well',
        ),
        migrations.AddField(
            model_name='delivery_boy',
            name='send_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='it_jobs',
            name='send_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='non_it_jobs',
            name='send_otp',
            field=models.BooleanField(default=False),
        ),
    ]
